

services:

  erp-api:
    build: .
    container_name: erp-api

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
      PORT: 3000

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - postgres

